CYO Report Code

library(haven)
library(caret)
library(dplyr)
library(stats)

#these four packages were utilised in this project

https://github.com/JCParsley/RProjectData.git

#above is the link to the github repository containing the data used. this data was renamed 'projectdata' for simplicity in this script

scatter.smooth(x=projectdata$f_dvage, y=projectdata$f_netinc1, main="Age and Pay")


sortedmonthlypay <- projectdata %>% filter(projectdata$f_fimngrs_dv > 0 & projectdata$f_fimngrs_dv < 14500)
scatter.smooth(x=sortedmonthlypay$f_dvage, y=sortedmonthlypay$f_fimngrs_dv, main="Age and Monthly Pay, Outliers Removed")

scatter.smooth(x=projectdata$f_dvage, y=projectdata$f_paynu_dv, main="Age and Net Pay per Month")

#many scatter plots were then run in the data visualisation stage - these three show how the age and pay variables specifically were explored

# the next section creates the test and training sets, as well as a more concise dataset, removing variables not used and removing nas

projectdatavariables <- select(projectdata, pidp, SatisfiedN, f_dvage, Rural, female, Employed, selfemploy, unemployed, degree, volfreq0, married, lnperspay, retired, student, Age2, healthsat, Leisuresat)
projectdatavariablesomit <- na.omit(projectdatavariables)
nrow(projectdatavariablesomit)

projectsetu <- projectdatavariablesomit$pidp
projectindex <- createDataPartition(projectsetu ,times=1, p=0.2, list = FALSE)

testset <- projectdatavariablesomit[projectindex,]
trainset <- projectdatavariablesomit[-projectindex,]
nrow(testset)

muhat <- mean(trainset$SatisfiedN)

fit <- lm(SatisfiedN ~ female + Employed + selfemploy + unemployed + retired + student + degree+ married + volfreq0 + Age2 + Rural + lnperspay, data=trainset)
summary(fit)

#initial linear regressions were run, followed by ones that included variables certain to increase the rsquare; this was a robustness check

fithealth <- lm(SatisfiedN ~ female + Employed + selfemploy + unemployed + retired + student + degree+ married + volfreq0 + Age2 + Rural + lnperspay + healthsat, data=trainset)
summary(fithealth)

fithealthleisure <- lm(SatisfiedN ~ female + Employed + selfemploy + unemployed + retired + student + degree+ married + volfreq0 + Age2 + Rural + lnperspay + healthsat + Leisuresat, data=trainset)
summary(fithealthleisure)

ruralmodel <- trainset %>% group_by(Rural) %>% summarize(b_i = mean(Rural - muhat))
ruralpredicted_ratings <- muhat + trainset %>% left_join(ruralmodel, by='Rural') %>% .$b_i
ruralmodelrmse <- RMSE(ruralpredicted_ratings, trainset$SatisfiedN)

volmodel <- trainset %>% group_by(volfreq0) %>% summarize(b_i = mean(volfreq0 - muhat))
volpredicted_ratings <- muhat + trainset %>% left_join(volmodel, by='volfreq0') %>% .$b_i
volmodelrmse <- RMSE(volpredicted_ratings, trainset$SatisfiedN)


studentmodel <- trainset %>% group_by(student) %>% summarize(b_i = mean(student - muhat))
studentpredicted_ratings <- muhat + trainset %>% left_join(studentmodel, by=‘student’) %>% .$b_i
studentmodelrmse <- RMSE(studentpredicted_ratings, trainset$SatisfiedN)

#rmses of each variable were created and compared, with the following three being selcected for this report

rmseresults <- data.frame(ruralmodelrmse)
rmseresults1 <- data.frame(volmodelrmse)
rmseresults2 <- data.frame(studentmodelrmse)
rmse_results <- data.frame(c(rmseresults1, rmseresults2, rmseresults))
rmse_results

#these results are demonstrative of the comparative effects eaj variable has